name: Build Docker Image with Version
on:
  push:
    tags:
      - "*-rc"

env:
  RELEASE_VERSION: ${{  github.ref_name }}

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Show tag versions
      run: echo $RELEASE_VERSION
    - name: Build Docker Image
      run: |
          cd laravel
          docker build \
          -t ghcr.io/nanangpras/laravel-app-1:$RELEASE_VERSION .
    - name: Login to github container registry
      run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u nanangpras --password-stdin
    - name: Push Docker Image
      run: docker push ghcr.io/nanangpras/laravel-app-1:$RELEASE_VERSION